
# Default values for filter functions.
QUERY_OFFSET = 0
EXCLUDE_AT_START = 21
EXCLUDE_AT_END = 21
DEFAULT_Q1 = 10
DEFAULT_Q2 = 30
DEFAULT_QF = 0
DEFAULT_Q0 = 1
RANDOMIZED_LENGTH = 2
N_RANDOM_REGIONS = 1
ADDITIONAL_MISMATCHES = 0
QUERY_OFFSET = 0

